# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.10.6
    hooks:
    # Update the uv lockfile
    -   id: uv-lock
-   repo: local
    hooks:
    -   id: codespell
        name: Codespell (spelling checker)
        entry: uv run codespell
        pass_filenames: false
        types_or: [ python, markdown, toml]
        language: system
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.2
    hooks:
    # Run the linter.
    -   id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi ]
-   repo: local
    hooks:
    -   id: pyrefly-check
        name: Pyrefly (type checking)
        entry: uv run pyrefly check
        pass_filenames: false  # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        types_or: [ python, pyi ]
        language: system
